### PR TITLE
Using SVGs!

### PR DESCRIPTION
**Pull request by dmaloneycalu**
Upped to v0.2.0.

Have split the dependencies into two directives, one for the wrapper and one for the actual radial. Can hold this open until more Karma tests can be written or include them as v0.2.1.

I'd like suggestions on the best way to include visual tests with this. I suppose I could rely on testing the svg and circles' attributes.

@StoicJester @jrit @Tathanen @thoughtpalette

### CODE REVIEW

**Comment by dmaloneycalu** [comment]
Here's a [fiddle](http://jsfiddle.net/mb7ohbjb/6/) with this implemented.

**Comment by jrit** [comment]
Have you seen this article? http://modernweb.com/2015/03/04/how-to-test-angularjs-svg-directives-2/ The second half is about comparing screenshots, which might be the most reliable option.

**Comment by dmaloneycalu** [comment]
Didn't know that protractor had a built in screenshot function. Since this directive is smaller, we'd be able to throw a couple of screenshot compares without it being too time consuming in testing. Will look into it for a future PR.

I'd like to build a tiny demo site for this. Something we could link at the top of the README or in the description so it can be seen in use.

**Comment by jrit** [comment]
Just setup a branch for a github.io site, that should live at vokal.github.io/angular-svg-radial

**Comment by dmaloneycalu** [comment]
Sweet, also something I didn't know. Thanks.

**Comment by jrit** [comment]
PR LGTM for now, clearly you are going to be making updates soon anyway

**Comment by jrit** [comment]
Can you drop some release notes into this PR so I can publish the 0.2 release?

**Comment by dmaloneycalu** [comment]
Release notes: v0.2.0
- Removed `radial-progress` directive and associated files
- Implemented `asr-wrap` and `asr-circle` directives using SVGs
- Updated tests

**Pull request merged**
